version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./bin/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=docker_flask_postgresql,docker_flask_postgresql_test
  web:
    build: .
    command: flask run
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    environment:
      FLASK_ENV: development
    depends_on:
      - db
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
